name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'
    - uses: actions/checkout@v3
    - run: corepack enable
    - run: corepack prepare pnpm@latest --activate
    - run: pnpm install
    - run: pnpm run deploy
      continue-on-error: true

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENTAN_GL_6D1E0E21 }}'

    - run: pnpm run deploy:frontend